### ISSUE TITLE
Unable to build React Native project after linking react-native-dns-lookup

### ISSUE THREAD

**Issue by Firaenix** [tableau/react-native-dns-lookup#1]
Hi,

I'm currently looking into DNS Lookup modules for react native and came across this project as it looked perfect for what I needed.

However after adding it to my project I have been unable to get my builds to work.

I ran react-native link react-native-dns-lookup and everything looks fine except for this error when I build.

The following error occurs in RNDnsLookup.m

<img width="734" alt="image" src="https://user-images.githubusercontent.com/8898038/67760032-81f8d300-fa7b-11e9-866a-b72d4b95a892.png">

Any help would be greatly appreciated.

**Comment by avertin** [comment]
Would you mind including some information about what version of react-native and xcode you are using?

**Comment by avertin** [comment]
Some suggestions to get the linking to work correctly:
1. After you `yarn add <>` / `npm install <>`  and before you do `react-native link <>`, try deleting the podspec file from  ⁨node_modules⁩/⁨react-native-dns-lookup⁩/⁨ios⁩/RNDnsLookup.podspec. Then try `react-native link react-native-dns-lookup`.

2. If the first suggestion doesn't work, you can always try manually linking the library for iOS https://facebook.github.io/react-native/docs/linking-libraries-ios#manual-linking
