### ISSUE TITLE
Can't build android release on react native version 0.61

### ISSUE THREAD

**Issue by tevin-maxwell** [tableau/react-native-dns-lookup#5]
<img width="1186" alt="Screen Shot 2020-04-24 at 7 07 59 PM" src="https://user-images.githubusercontent.com/46663993/80210974-ebd6eb80-865e-11ea-9fbd-b55b15e1d29e.png">

**Comment by avertin** [comment]
I was unable to reproduce this issue with a sample project using react-native 0.63.2 and react-native-dns-lookup 1.0.3.  

For react-native >= 0.60 linking occurs automatically. If you manually linked the library, you can run `react-native unlink react-native-dns-lookup` and then rebuild the app `yarn react-native run-android`. 

Sample project: https://github.com/avertin/DnsTest/blob/master/App.js#L30
Autolinking: https://github.com/react-native-community/cli/blob/master/docs/autolinking.md
