### ISSUE TITLE
getIpAddresses - TypeError: null is not an object

### ISSUE THREAD

**Issue by ajones2k** [tableau/react-native-dns-lookup#6]
When building on iOS with XCode 11.4.1 and RN 0.62.2 I get the error, "TypeError: null is not an object (evaluating RNDnsLookup.getIpAddresses)" at runtime when getIpAddressesForHostname is called. I have tried both auto and manual linking. My Android build runs without any issue.

**Comment by bernstein7** [comment]
Actually I have the same thing on Android (both emulator and real device) and can't find the way to fix it by my own

**Comment by medienJan** [comment]
I also have the same problem. Did anyone find a solution for this? I'm on Xcode 11.6 and RN 0.63.2.

**Comment by medienJan** [comment]
Is it possible to get an example project where this is set up and linked correctly?

**Comment by avertin** [comment]
I reproduced the issue on iOS and I determined that it was an issue with podspec file. I've fixed it in [version 1.0.3 of the library](https://github.com/tableau/react-native-dns-lookup/releases/tag/v1.0.3). The library should now autolink if you are using a version of RN >= 60.0. No need to run `react-native link` or do manual linking.

After updating `react-native-dns-lookup` to 1.0.3, you'll need to do a pod install `cd ios && pod install && cd ..`, then rebuild the app `yarn react-native run-ios`.  @ajones2k please try it out. 


I still need to investigate to see if I can reproduced the same issue on Android.

**Comment by avertin** [comment]
I was unable to reproduce the Android issue with a sample project using react-native 0.63.2 and react-native-dns-lookup 1.0.3.

For react-native >= 0.60 linking occurs automatically. If you manually linked the library, you can run `react-native unlink react-native-dns-lookup` and then rebuild the app `yarn react-native run-android`.

@medienJan @bernstein7 please see the sample project. 
Sample project: https://github.com/avertin/DnsTest/blob/master/App.js#L30

**Comment by boblitex** [comment]
back in 2022 with this same exact issue. React Native 0.68.0. do I open a new Issue or can we look into this again? @avertin
